# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -q pipenv codecov
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --config=.flake8
    - name: Run tests on Pytest
      run: |
        pipenv run pytest --cov=libpythonpro

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
